services:
  userservice:
    image: userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile

  paymentservice:
    image: paymentservice
    build:
      context: .
      dockerfile: PaymentService/Dockerfile

  notificationservice:
    image: notificationservice
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
